language: c
dist: trusty
sudo: true
env:
  - PGVERSION=10.3
services:
    - postgres
addons:
  postgresql: $PGVERSION
before_install:
  - wget https://gist.github.com/cloewen8/257253a1a4d23111315bed613681aca3/raw
  - sudo bash -c 'echo yes | cpan TAP::Parser::SourceHandler::pgTAP'
  - bash pg-pgtap-install.sh
install:
  - cat install.log
script:
  - export PERL5LIB=~/perl5/lib/perl5
  - cd test && ~/perl5/bin/pg_prove -h localhost -p 55436 -d skel_test -U postgres tests/run_*.sql