language: c
dist: trusty
sudo: true
env:
  - PGVERSION=9.2
    db_host=localhost
    db_port=55436
    db_name=skel_test
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/C-Pro/8491912/raw/pg-pgtap-install.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo bash -c 'echo yes | cpan TAP::Parser::SourceHandler::pgTAP'
  - bash pg-pgtap-install.sh
install:
  - echo 'test' | bash ./install.sh
  - cat install.log
script:
  - cd test && pg_prove -h $db_host -p $db_port -d $db_name tests/run_*.sql