language: c
dist: trusty
sudo: true
env:
  global:
    - PGVERSION=10
services:
    - postgres
addons:
  postgresql: $PGVERSION
before_install:
  - wget https://gist.githubusercontent.com/cloewen8/257253a1a4d23111315bed613681aca3/raw/91ef42dd6067690969598a185c72fcf539fbc3c5/pg-pgtap-install.sh
  - sudo bash -c 'echo yes | cpan TAP::Parser::SourceHandler::pgTAP'
  - bash pg-pgtap-install.sh
script:
  - cd test && pg_prove -h localhost -d skel_test -U postgres tests/run_*.sql